/**
 * SVG Export Service
 * 
 * Generates SVG files from tool outlines with correct real-world scale.
 */

import type { Point2D } from './geometry';

// ============================================================================
// Types
// ============================================================================

export interface SVGExportOptions {
  /** Unit for measurements (default: 'mm') */
  unit?: 'mm' | 'in' | 'px';
  /** Include dimension labels */
  includeDimensions?: boolean;
  /** Stroke width in mm */
  strokeWidth?: number;
  /** Stroke color */
  strokeColor?: string;
  /** Fill color (or 'none') */
  fillColor?: string;
  /** Add margin around content (in mm) */
  margin?: number;
}

export interface ToolOutlineExport {
  id: string;
  name: string;
  points: Point2D[];
  color: string;
}

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_OPTIONS: Required<SVGExportOptions> = {
  unit: 'mm',
  includeDimensions: false,
  strokeWidth: 0.5,
  strokeColor: '#000000',
  fillColor: 'none',
  margin: 5,
};

// ============================================================================
// SVG Generation
// ============================================================================

/**
 * Generate SVG string from tool outlines
 */
export function generateSVG(
  outlines: ToolOutlineExport[],
  pixelsPerMm: number,
  options: SVGExportOptions = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  
  if (outlines.length === 0) {
    return createEmptySVG(opts);
  }
  
  // Calculate bounding box of all outlines in mm
  const bounds = calculateBounds(outlines, pixelsPerMm);
  
  // Add margin
  const margin = opts.margin;
  const width = bounds.maxX - bounds.minX + margin * 2;
  const height = bounds.maxY - bounds.minY + margin * 2;
  
  // Offset to center content
  const offsetX = -bounds.minX + margin;
  const offsetY = -bounds.minY + margin;
  
  // Build SVG
  const paths = outlines.map((outline) => {
    const pathData = pointsToSVGPath(outline.points, pixelsPerMm, offsetX, offsetY);
    return `    <path
      id="${outline.id}"
      d="${pathData}"
      fill="${opts.fillColor}"
      stroke="${outline.color || opts.strokeColor}"
      stroke-width="${opts.strokeWidth}"
      data-name="${escapeXml(outline.name)}"
    />`;
  }).join('\n');
  
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="${width.toFixed(2)}${opts.unit}"
  height="${height.toFixed(2)}${opts.unit}"
  viewBox="0 0 ${width.toFixed(2)} ${height.toFixed(2)}"
>
  <title>ToolTrace Export</title>
  <desc>Generated by ToolTrace</desc>
  
  <g id="tool-outlines">
${paths}
  </g>
</svg>`;
}

/**
 * Export SVG and trigger download
 */
export function downloadSVG(
  outlines: ToolOutlineExport[],
  pixelsPerMm: number,
  filename: string = 'tooltrace-export.svg',
  options: SVGExportOptions = {}
): void {
  const svgContent = generateSVG(outlines, pixelsPerMm, options);
  
  const blob = new Blob([svgContent], { type: 'image/svg+xml' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.svg') ? filename : `${filename}.svg`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

// ============================================================================
// Helper Functions
// ============================================================================

function createEmptySVG(opts: Required<SVGExportOptions>): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="100${opts.unit}"
  height="100${opts.unit}"
  viewBox="0 0 100 100"
>
  <title>ToolTrace Export - Empty</title>
</svg>`;
}

function calculateBounds(
  outlines: ToolOutlineExport[],
  pixelsPerMm: number
): { minX: number; minY: number; maxX: number; maxY: number } {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  
  for (const outline of outlines) {
    for (const p of outline.points) {
      const x = p.x / pixelsPerMm;
      const y = p.y / pixelsPerMm;
      minX = Math.min(minX, x);
      minY = Math.min(minY, y);
      maxX = Math.max(maxX, x);
      maxY = Math.max(maxY, y);
    }
  }
  
  return { minX, minY, maxX, maxY };
}

function pointsToSVGPath(
  points: Point2D[],
  pixelsPerMm: number,
  offsetX: number,
  offsetY: number
): string {
  if (points.length === 0) return '';
  
  const parts: string[] = [];
  
  // Move to first point
  const first = points[0];
  parts.push(`M ${((first.x / pixelsPerMm) + offsetX).toFixed(3)} ${((first.y / pixelsPerMm) + offsetY).toFixed(3)}`);
  
  // Line to remaining points
  for (let i = 1; i < points.length; i++) {
    const p = points[i];
    parts.push(`L ${((p.x / pixelsPerMm) + offsetX).toFixed(3)} ${((p.y / pixelsPerMm) + offsetY).toFixed(3)}`);
  }
  
  // Close path
  parts.push('Z');
  
  return parts.join(' ');
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
